export const userDefaultConfig = {
    level: 1,
    balance: 0n,
    energy: 200n,
    earnByTapBoosterLevel: 0,
    energyPerSecondBoosterLevel: 0,
    maxEnergyBoosterLevel: 0,
    earnPerHourBonus: 0n,
    lastEnergyUpdateTimestamp: 0,
    lastTapTimestamp: 0,
    lastDailyClaimTimestamp: 0,
    prevDailyClaimTimestamp: 0,
    dailyStreak: 0,
    lastFullEnergyBonusTimestamp: 0,
    fullEnergyBonusCount: 0,
}